<?php

namespace app\controllers;

use app\models\ScreenshotForm;
use app\models\Screenshots;
use app\models\Users;
use yii\filters\AccessControl;

class ShareController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                    ],
                ],
            ],
        ];
    }

    public function actionUploadImage()
    {
        $user = Users::findOne(['api_key'=>$_POST['api_key']]);
        if($user == null) return false;

        foreach($_FILES as $file) {
            $generate_id = md5(time()."s".rand(0,1000000));
            $filename = $generate_id.".".explode("/", $file['type'])[1];
            move_uploaded_file($file['tmp_name'], \Yii::getAlias('@webroot')."/uploads/".$filename);
            // Userdaten anheften
            $screen = new Screenshots();
            $screen->uploader = $user->id;
            $screen->file_id = $filename;
            $screen->description = null;
            $screen->is_private = true;

            // Exif-Daten extrahieren
            $exif_data = @json_encode(exif_read_data(\Yii::getAlias("@webroot")."/uploads/".$filename));
            if($exif_data == null || empty($exif_data)) $exif_data = "{}";
            $screen->exif_data = $exif_data;

            // Model speichern und weiterleiten
            $screen->save();
            return json_encode([
                "url_direct" => \Yii::getAlias('@webUrl')."/uploads/".$filename,
                "url_thumbnail" => \Yii::getAlias('@webUrl')."/uploads/thumb/".$filename,
                "url_forcedelete" => \Yii::getAlias('@webUrl')."/delete?file=".md5($filename.$user->id),
            ]);
        }

        return;
    }

}
